// LOCKED (Rayan). Yaso: make these pass. Do NOT edit this file.
import { describe, expect, it } from "vitest";
import { STRINGS, buildReportScript, buildSmsSummary, t } from "@/content";
import { formatINR } from "@/lib/core/format";
import { makeView } from "./fixtures";
import type { Lang } from "@/types";

const LANGS: Lang[] = ["en", "hi", "kn"];
const DEVANAGARI = /[ऀ-ॿ]/;
const KANNADA = /[ಀ-೿]/;
const BAD = /undefined|null|NaN|TODO|STUB|\[object/;

describe("SMS summary", () => {
  for (const lang of LANGS) {
    it(`${lang}: with commitment`, () => {
      const s = buildSmsSummary(makeView(true, lang), lang);
      expect(s.length).toBeLessThanOrEqual(320);
      expect(s).toContain("A-0142");
      expect(s).toContain("CMP88213");
      expect(s).toContain(formatINR(450000));
      expect(s).not.toMatch(BAD);
    });
    it(`${lang}: without commitment`, () => {
      const s = buildSmsSummary(makeView(false, lang), lang);
      expect(s.length).toBeLessThanOrEqual(320);
      expect(s).toContain("A-0142");
      expect(s).not.toMatch(BAD);
    });
  }
  it("hi is in Devanagari, kn is in Kannada script", () => {
    expect(buildSmsSummary(makeView(true, "hi"), "hi")).toMatch(DEVANAGARI);
    expect(buildSmsSummary(makeView(true, "kn"), "kn")).toMatch(KANNADA);
  });
});

describe("report-back call script", () => {
  for (const lang of LANGS) {
    it(`${lang}: speaks the outcome`, () => {
      const s = buildReportScript(makeView(true, lang), lang);
      expect(s).toContain("CMP88213");
      expect(s).toContain("Ravi");
      expect(s.length).toBeGreaterThan(60);
      expect(s.length).toBeLessThan(700);
      expect(s).not.toMatch(BAD);
    });
    it(`${lang}: no commitment => says the company did not give a ticket`, () => {
      const s = buildReportScript(makeView(false, lang), lang);
      expect(s.length).toBeGreaterThan(40);
      expect(s).not.toMatch(BAD);
    });
  }
  it("hi/kn scripts are in their own script", () => {
    expect(buildReportScript(makeView(true, "hi"), "hi")).toMatch(DEVANAGARI);
    expect(buildReportScript(makeView(true, "kn"), "kn")).toMatch(KANNADA);
  });
});

describe("UI strings", () => {
  it("all languages have exactly the same keys, none empty", () => {
    const keys = Object.keys(STRINGS.en).sort();
    for (const lang of LANGS) {
      expect(Object.keys(STRINGS[lang]).sort()).toEqual(keys);
      for (const k of keys) expect(STRINGS[lang][k as keyof typeof STRINGS.en].trim().length).toBeGreaterThan(0);
    }
  });
  it("hi and kn are actually translated", () => {
    expect(t("liveCases", "hi")).toMatch(DEVANAGARI);
    expect(t("escalate", "hi")).toMatch(DEVANAGARI);
    expect(t("liveCases", "kn")).toMatch(KANNADA);
    expect(t("escalate", "kn")).toMatch(KANNADA);
  });
});
