// LOCKED (Rayan). Yaso: make these pass. Do NOT edit this file.
import { describe, expect, it } from "vitest";
import { DEMO_SCRIPTS } from "@/mock/scripts";
import { reduceEvents } from "@/lib/core/reduce";
import { ADVOCATE_STATES, type AdvocallEvent, type DemoScript } from "@/types";

function stamp(s: DemoScript): AdvocallEvent[] {
  let t = Date.parse("2026-09-26T05:00:00.000Z");
  return s.steps.map((st, i) => {
    t += st.delayMs;
    return { ...st.event, id: `e${i}`, at: new Date(t).toISOString() } as AdvocallEvent;
  });
}
const byId = (id: string) => DEMO_SCRIPTS.find((s) => s.id === id);

describe("all demo scripts", () => {
  it("ids are unique and required scripts exist", () => {
    const ids = DEMO_SCRIPTS.map((s) => s.id);
    expect(new Set(ids).size).toBe(ids.length);
    for (const req of ["quick", "upi", "ecom", "refusal"]) expect(ids).toContain(req);
  });

  for (const s of DEMO_SCRIPTS) {
    describe(`script "${s.id}"`, () => {
      it("is well-formed", () => {
        expect(s.title.length).toBeGreaterThan(3);
        expect(s.steps[0].event.type).toBe("case.created");
        const caseId = s.steps[0].event.caseId;
        const total = s.steps.reduce((a, st) => a + st.delayMs, 0);
        expect(total).toBeGreaterThanOrEqual(20_000);
        expect(total).toBeLessThanOrEqual(180_000);
        for (const st of s.steps) {
          expect(st.delayMs).toBeGreaterThanOrEqual(0);
          expect(st.event.caseId).toBe(caseId);
        }
      });
      it("only references calls that were started earlier", () => {
        const started = new Set<string>();
        for (const { event: e } of s.steps) {
          if (e.type === "call.started") started.add(e.data.call.id);
          if (e.type === "call.state" || e.type === "call.ended") expect(started.has(e.data.callId)).toBe(true);
          if (e.type === "transcript") expect(started.has(e.data.line.callId)).toBe(true);
        }
      });
      it("reduces to exactly one case view without errors", () => {
        const views = reduceEvents(stamp(s));
        expect(Object.keys(views)).toHaveLength(1);
      });
      it("advocate states move forward (PUSH_BACK max twice)", () => {
        const last: Record<string, number> = {};
        const pushBacks: Record<string, number> = {};
        for (const { event: e } of s.steps) {
          if (e.type !== "call.state") continue;
          const id = e.data.callId;
          const idx = ADVOCATE_STATES.indexOf(e.data.state);
          expect(idx).toBeGreaterThanOrEqual(last[id] ?? -1); // never goes backwards (repeating is ok)
          last[id] = idx;
          if (e.data.state === "PUSH_BACK") pushBacks[id] = (pushBacks[id] ?? 0) + 1;
        }
        for (const n of Object.values(pushBacks)) expect(n).toBeLessThanOrEqual(2);
      });
    });
  }
});

describe("hero script: upi", () => {
  it("has the full golden path", () => {
    const s = byId("upi")!;
    const types = s.steps.map((x) => x.event.type);
    for (const t of ["case.created", "rule.matched", "call.started", "call.state", "transcript", "commitment.recorded", "call.ended", "message.sent"]) {
      expect(types).toContain(t);
    }
    const legs = s.steps.flatMap((x) => (x.event.type === "call.started" ? [x.event.data.call.leg] : []));
    expect(legs).toEqual(["intake", "advocate", "report"]);
    const matched = s.steps.find((x) => x.event.type === "rule.matched")!.event;
    expect(matched.type === "rule.matched" && matched.data.match.ruleId).toBe("R1");
    expect(types.filter((t) => t === "transcript").length).toBeGreaterThanOrEqual(12);
    const view = Object.values(reduceEvents(stamp(s)))[0];
    expect(view.commitment?.ticketNo).toBeTruthy();
    expect(view.case.status).toBe("promised");
  });
});

describe("refusal script", () => {
  it("company refuses twice => no commitment, case failed or escalated", () => {
    const s = byId("refusal")!;
    const view = Object.values(reduceEvents(stamp(s)))[0];
    expect(view.commitment).toBeNull();
    expect(["failed", "escalated"]).toContain(view.case.status);
    const pushBacks = s.steps.filter((x) => x.event.type === "call.state" && x.event.data.state === "PUSH_BACK");
    expect(pushBacks).toHaveLength(2);
  });
});

describe("ecom script", () => {
  it("matches R2", () => {
    const s = byId("ecom")!;
    const matched = s.steps.find((x) => x.event.type === "rule.matched")!.event;
    expect(matched.type === "rule.matched" && matched.data.match.ruleId).toBe("R2");
  });
});
