// LOCKED (Rayan). Agastya: make these pass. Do NOT edit this file.
import { describe, expect, it } from "vitest";
import { RULES, addDays, daysBetween, isValidYmd, matchRule, buildEscalationPacket } from "@/lib/rules";
import { formatINR } from "@/lib/core/format";
import { commitment, upiCase, upiInput } from "./fixtures";

describe("dates", () => {
  it("isValidYmd", () => {
    expect(isValidYmd("2026-09-20")).toBe(true);
    expect(isValidYmd("2024-02-29")).toBe(true);
    expect(isValidYmd("2026-02-29")).toBe(false);
    expect(isValidYmd("2026-02-30")).toBe(false);
    expect(isValidYmd("20-09-2026")).toBe(false);
    expect(isValidYmd("")).toBe(false);
  });
  it("addDays", () => {
    expect(addDays("2026-09-20", 1)).toBe("2026-09-21");
    expect(addDays("2026-09-30", 1)).toBe("2026-10-01");
    expect(addDays("2026-12-31", 1)).toBe("2027-01-01");
    expect(addDays("2026-02-28", 1)).toBe("2026-03-01");
    expect(addDays("2026-08-01", 30)).toBe("2026-08-31");
    expect(addDays("2026-09-21", -1)).toBe("2026-09-20");
  });
  it("daysBetween", () => {
    expect(daysBetween("2026-09-21", "2026-09-26")).toBe(5);
    expect(daysBetween("2026-09-26", "2026-09-21")).toBe(-5);
    expect(daysBetween("2026-09-26", "2026-09-26")).toBe(0);
    expect(daysBetween("2026-12-30", "2027-01-02")).toBe(3);
  });
});

describe("rulebook data", () => {
  it("every rule is complete and sourced", () => {
    for (const r of Object.values(RULES)) {
      expect(r.sourceUrl.startsWith("https://")).toBe(true);
      expect(r.escalation.url.startsWith("https://")).toBe(true);
      expect(r.summary).not.toMatch(/TODO/);
      expect(r.sourceName).not.toMatch(/TODO/);
      expect(r.citeText).not.toMatch(/TODO/);
      expect(r.goalOnCall.length).toBeGreaterThan(0);
    }
  });
  it("R1 and R2 are verified and citable", () => {
    expect(RULES.R1.verified).toBe(true);
    expect(RULES.R2.verified).toBe(true);
    expect(RULES.R1.citeText.length).toBeGreaterThan(20);
    expect(RULES.R2.citeText.length).toBeGreaterThan(20);
  });
});

describe("matchRule: R1 failed UPI", () => {
  it("5 days late => Rs 500 compensation", () => {
    const m = matchRule(upiInput, "2026-09-26");
    expect(m.ruleId).toBe("R1");
    expect(m.rule.id).toBe("R1");
    expect(m.claimable).toBe(true);
    expect(m.deadline).toBe("2026-09-21");
    expect(m.daysLate).toBe(5);
    expect(m.compensationPaise).toBe(50000);
    expect(m.totalAtStakePaise).toBe(500000);
    expect(m.explanation).toContain(formatINR(450000));
    expect(m.explanation).toContain(formatINR(50000));
    expect(m.pushBackLine).toContain("RBI");
    expect(m.pushBackLine).toContain("T+1");
  });
  it("on deadline day => not late", () => {
    const m = matchRule(upiInput, "2026-09-21");
    expect(m.daysLate).toBe(0);
    expect(m.compensationPaise).toBe(0);
    expect(m.totalAtStakePaise).toBe(450000);
  });
  it("same day => not late", () => {
    expect(matchRule(upiInput, "2026-09-20").daysLate).toBe(0);
  });
});

describe("matchRule: R2 e-commerce", () => {
  it("deadline = complaint date + 30 days, no statutory compensation", () => {
    const m = matchRule(
      { ...upiInput, category: "ecom_refund", company: "Flipkart", incidentDate: "2026-08-01", amountPaise: 129900 },
      "2026-09-26",
    );
    expect(m.ruleId).toBe("R2");
    expect(m.claimable).toBe(true);
    expect(m.deadline).toBe("2026-08-31");
    expect(m.daysLate).toBe(26);
    expect(m.compensationPaise).toBe(0);
    expect(m.totalAtStakePaise).toBe(129900);
    expect(m.explanation).toContain(formatINR(129900));
  });
});

describe("matchRule: R3 telecom and fallback", () => {
  it("R3 only claimable if verified", () => {
    const m = matchRule({ ...upiInput, category: "telecom_billing", company: "Airtel" }, "2026-09-26");
    expect(m.ruleId).toBe("R3");
    expect(m.claimable).toBe(RULES.R3.verified);
    expect(m.compensationPaise).toBe(0);
    if (!RULES.R3.verified) expect(m.pushBackLine).not.toMatch(/TRAI/);
  });
  it("other => FALLBACK, no legal claim", () => {
    const m = matchRule({ ...upiInput, category: "other", company: "Some Shop" }, "2026-09-26");
    expect(m.ruleId).toBe("FALLBACK");
    expect(m.claimable).toBe(false);
    expect(m.deadline).toBeNull();
    expect(m.compensationPaise).toBe(0);
    expect(m.totalAtStakePaise).toBe(450000);
    expect(m.pushBackLine.toLowerCase()).toContain("complaint number");
    expect(m.pushBackLine).not.toMatch(/RBI|TRAI|Rule/);
  });
});

describe("matchRule: bad input", () => {
  it("throws on invalid amount or date", () => {
    expect(() => matchRule({ ...upiInput, amountPaise: -5 }, "2026-09-26")).toThrow();
    expect(() => matchRule({ ...upiInput, amountPaise: 0 }, "2026-09-26")).toThrow();
    expect(() => matchRule({ ...upiInput, amountPaise: 12.5 }, "2026-09-26")).toThrow();
    expect(() => matchRule({ ...upiInput, incidentDate: "20-09-2026" }, "2026-09-26")).toThrow();
  });
  it("incident in the future => not late", () => {
    const m = matchRule({ ...upiInput, incidentDate: "2026-09-30" }, "2026-09-26");
    expect(m.daysLate).toBe(0);
    expect(m.compensationPaise).toBe(0);
  });
});

describe("buildEscalationPacket", () => {
  it("R1 with commitment", () => {
    const m = matchRule(upiInput, "2026-09-26");
    const p = buildEscalationPacket(upiCase, m, commitment, "2026-10-02");
    expect(p.caseId).toBe("A-0142");
    expect(p.to).toMatch(/RBI/);
    expect(p.channelUrl).toBe("https://cms.rbi.org.in");
    expect(p.subject.length).toBeGreaterThan(10);
    for (const s of ["A-0142", "HDFC Bank", "UPI4829301", "CMP88213", formatINR(450000), "Ravi Kumar"]) {
      expect(p.body).toContain(s);
    }
    expect(p.facts).toContainEqual(["Amount", formatINR(450000)]);
    expect(p.facts).toContainEqual(["Ticket number", "CMP88213"]);
    expect(p.body).not.toMatch(/undefined|null|NaN|TODO|STUB/);
  });
  it("R1 without commitment", () => {
    const m = matchRule(upiInput, "2026-09-26");
    const p = buildEscalationPacket(upiCase, m, null, "2026-09-26");
    expect(p.body).not.toMatch(/undefined|null|NaN|TODO|STUB/);
    expect(p.facts).toContainEqual(["Ticket number", "Not provided"]);
  });
  it("R2 goes to National Consumer Helpline", () => {
    const input = { ...upiInput, category: "ecom_refund" as const, company: "Flipkart" };
    const m = matchRule(input, "2026-09-26");
    const p = buildEscalationPacket({ ...upiCase, ...input }, m, null, "2026-09-26");
    expect(p.to).toMatch(/National Consumer Helpline/);
    expect(p.phone).toBe("1915");
    expect(p.channelUrl).toContain("consumerhelpline.gov.in");
  });
});
