// Owner: YASO. Dashboard UI labels in 3 languages. Vaishnavi's components call t("key", lang).
// Placeholders like {n} / {id} are filled with fill(t("key", lang), { n: 3 }).
import type { Lang } from "@/types";

const en = {
  appName: "Advocall",
  tagline: "Your AI advocate on hold, so you don't have to be",
  liveCases: "Live cases",
  atStake: "At stake",
  recovered: "Recovered",
  ruleApplied: "Rule applied",
  deadline: "Deadline",
  daysLate: "Days late",
  compensation: "Compensation owed",
  ticket: "Ticket number",
  promisedBy: "Promised by",
  transcript: "Live transcript",
  timeline: "Timeline",
  escalate: "Deadline missed: escalate",
  startDemo: "Run demo",
  reset: "Reset",
  connected: "Live",
  disconnected: "Offline",
  noCases: "No cases yet. Call Advocall or run a demo.",
  caseList: "Cases",
  caseDetail: "Case detail",
  liveOps: "Live operations",
  amountDisputed: "Amount disputed",
  customer: "Customer",
  reference: "Reference",
  callProgress: "Call progress",
  commitment: "Commitment",
  waitingTicket: "Waiting for ticket number…",
  escalationPacket: "Escalation packet",
  copyLetter: "Copy letter",
  copied: "Copied",
  smsSent: "SMS text for the user (preview)",
  noTranscript: "No conversation yet",
  computedByEngine: "Computed by rights engine, not by AI",
  noLegalClaim: "No legal claim, standard complaint only",
  source: "Source",
  intakeCall: "Intake call",
  advocateCall: "Call to company",
  reportCall: "Report-back call",
  activeCases: "Active cases",
  committed: "Committed",
  callsMade: "Calls made",
  present: "Present",

  // header + layout
  demo: "Demo",
  chooseDemo: "Choose a demo",
  details: "Details",
  chat: "Transcript",
  presentBanner: "Projector mode: live conversation and legal rights",
  exitPresent: "Exit (P / Esc)",
  inFlight: "In flight",
  disputed: "Disputed",
  ticketConfirmed: "Ticket confirmed",
  voiceLegs: "Voice legs",
  newestFirst: "Newest first",
  // case header
  incident: "Incident",
  notProvided: "Not provided",
  issue: "Issue",
  // rule card
  matchingRule: "Matching the case to a rule…",
  none: "None",
  nDaysLate: "{n} days late",
  oneDayLate: "1 day late",
  onTime: "On time",
  // call progress
  advocateProgress: "Advocate call progress",
  advocateProgressSub: "IVR, hold and negotiation, step by step",
  live: "Live",
  done: "Done",
  pending: "Pending",
  queued: "Queued",
  ringing: "Ringing",
  failed: "Failed",
  outcome: "Outcome",
  stepDISCLOSE: "Disclose",
  stepNAVIGATE: "IVR menu",
  stepHOLD: "Hold",
  stepSTATE_CASE: "State case",
  stepASK: "Ask ticket",
  stepPUSH_BACK: "Push back",
  stepVERIFY: "Verify",
  stepCAPTURE: "Capture",
  stepCLOSE: "Close",
  // commitment
  noTicket: "No ticket issued",
  noTicketSub: "The company did not register a complaint",
  declined: "Declined",
  safetyLimit: "Safety limit reached",
  refusedBody: "The company refused after {n} polite push-backs. Advocall never pushes more than twice, so it ended the call and prepared a complaint for the regulator.",
  unreachedBody: "Advocall could not get a complaint registered on this call, so it prepared a complaint for the regulator.",
  awaiting: "Awaiting",
  officialRef: "Official company reference",
  insistHint: "Advocall asks for a formal complaint and captures the reference number.",
  commitmentCaptured: "Commitment captured",
  acknowledged: "Acknowledged",
  noDate: "No date given",
  delayComp: "Delay compensation",
  notAgreed: "Not agreed",
  readBack: "Ticket read back and confirmed by the company",
  // escalation
  escalationTitle: "Regulator escalation",
  escalationSub: "Complaint letter generator",
  escalationHint: "If the company misses its date or refuses, Advocall drafts a complaint letter for the regulator (RBI Ombudsman or National Consumer Helpline). You file it.",
  preparing: "Preparing…",
  packetReady: "Complaint ready to file",
  portal: "Portal",
  subject: "Subject",
  keyFacts: "Key facts",
  letter: "Complaint letter",
  // timeline
  events: "events",
  noEvents: "No events yet.",
  evCreated: "Case {id} created",
  evStatus: "Status: {s}",
  evRule: "Rule {id}: {title}",
  evClaimable: "Legal right applies",
  evStandard: "Standard complaint",
  evCallStarted: "{leg} started",
  evState: "Advocate step: {s}",
  evCallEnded: "{leg} ended",
  evCallFailed: "{leg} failed",
  evTicket: "Ticket {t} captured",
  evResolutionBy: "Resolution by {d}",
  evEscalation: "Complaint prepared",
  evEscalationTo: "For {to}",
  evSms: "SMS text for {to}",
  followupCall: "Follow-up call",
  // transcript
  lines: "lines",
  aiName: "Advocall AI",
  user: "User",
  company: "Company",
  noTranscriptHint: "Run a demo or start a live call to watch the conversation stream in.",
  // sms
  noSms: "No SMS yet",
  smsHint: "After the calls, Advocall texts the customer the ticket number and date.",
  smsPreviewNote: "Preview: shown here, not sent (SMS needs a registered sender)",
  // status badge
  statusIntake: "Intake",
  statusOpen: "Open",
  statusCalling: "Calling",
  statusPromised: "Promised",
  statusResolved: "Resolved",
  statusEscalated: "Escalated",
  statusFailed: "Failed",
  // empty state
  aiAdvocate: "AI consumer advocate",
  emptyHint: "Advocall calls customer care for you, waits on hold, cites your rights, and gets a complaint number and a date.",
  runHero: "Run UPI demo",
  runQuick: "Quick demo (5× speed)",
  // rights timeline card
  rightsTitle: "Your rights timeline",
  rightsSub: "Computed by the rights engine",
  msIncident: "Incident",
  msDeadline: "Legal deadline",
  msPromised: "Company promised",
  msToday: "Today",
  msEscalate: "Escalate if unresolved",
  // live call menu
  liveCall: "Live call",
  liveCallTitle: "Start a real call",
  liveOff: "Live calls are off. Add the keys in .env.local and set MODE=live.",
  yourPhone: "Your phone (team only)",
  yourName: "Your name (optional)",
  callMe: "Call me",
  calling: "Calling…",
  browserCall: "Talk in the browser instead",
};

export type StringKey = keyof typeof en;

const hi: Record<StringKey, string> = {
  appName: "Advocall",
  tagline: "होल्ड पर आपका AI वकील, ताकि आपको इंतज़ार न करना पड़े",
  liveCases: "लाइव केस",
  atStake: "दांव पर राशि",
  recovered: "वापस मिला",
  ruleApplied: "लागू नियम",
  deadline: "समय सीमा",
  daysLate: "दिन की देरी",
  compensation: "बकाया मुआवज़ा",
  ticket: "शिकायत नंबर",
  promisedBy: "वादा की गई तारीख",
  transcript: "लाइव बातचीत",
  timeline: "टाइमलाइन",
  escalate: "समय सीमा निकल गई: आगे शिकायत करें",
  startDemo: "डेमो चलाएँ",
  reset: "रीसेट",
  connected: "लाइव",
  disconnected: "ऑफ़लाइन",
  noCases: "अभी कोई केस नहीं। Advocall को कॉल करें या डेमो चलाएँ।",
  caseList: "केस सूची",
  caseDetail: "केस विवरण",
  liveOps: "लाइव ऑपरेशन्स",
  amountDisputed: "विवादित राशि",
  customer: "ग्राहक",
  reference: "रेफ़रेंस",
  callProgress: "कॉल प्रगति",
  commitment: "कंपनी का वादा",
  waitingTicket: "शिकायत नंबर की प्रतीक्षा…",
  escalationPacket: "शिकायत पत्र (एस्केलेशन पैकेट)",
  copyLetter: "पत्र कॉपी करें",
  copied: "कॉपी हो गया",
  smsSent: "यूज़र के लिए SMS (प्रीव्यू)",
  noTranscript: "अभी कोई बातचीत नहीं",
  computedByEngine: "राइट्स इंजन द्वारा निर्धारित, AI द्वारा नहीं",
  noLegalClaim: "कोई वैधानिक दावा नहीं, केवल सामान्य शिकायत",
  source: "स्रोत",
  intakeCall: "इंटेक कॉल",
  advocateCall: "कंपनी को कॉल",
  reportCall: "रिपोर्ट-बैक कॉल",
  activeCases: "सक्रिय केस",
  committed: "वादा मिला",
  callsMade: "की गई कॉल",
  present: "प्रस्तुति",

  demo: "डेमो",
  chooseDemo: "डेमो चुनें",
  details: "विवरण",
  chat: "बातचीत",
  presentBanner: "प्रोजेक्टर मोड: लाइव बातचीत और कानूनी अधिकार",
  exitPresent: "बाहर निकलें (P / Esc)",
  inFlight: "जारी",
  disputed: "विवादित",
  ticketConfirmed: "शिकायत नंबर मिला",
  voiceLegs: "वॉइस कॉल",
  newestFirst: "नए पहले",
  incident: "घटना",
  notProvided: "नहीं दिया",
  issue: "समस्या",
  matchingRule: "केस के लिए नियम ढूँढा जा रहा है…",
  none: "कोई नहीं",
  nDaysLate: "{n} दिन देर",
  oneDayLate: "1 दिन देर",
  onTime: "समय पर",
  advocateProgress: "कंपनी कॉल की प्रगति",
  advocateProgressSub: "IVR, होल्ड और बातचीत, कदम दर कदम",
  live: "लाइव",
  done: "पूरा",
  pending: "बाकी",
  queued: "कतार में",
  ringing: "घंटी बज रही है",
  failed: "विफल",
  outcome: "नतीजा",
  stepDISCLOSE: "परिचय",
  stepNAVIGATE: "IVR मेनू",
  stepHOLD: "होल्ड",
  stepSTATE_CASE: "केस बताया",
  stepASK: "नंबर माँगा",
  stepPUSH_BACK: "ज़ोर दिया",
  stepVERIFY: "सत्यापन",
  stepCAPTURE: "दर्ज किया",
  stepCLOSE: "समाप्त",
  noTicket: "कोई शिकायत नंबर नहीं",
  noTicketSub: "कंपनी ने शिकायत दर्ज नहीं की",
  declined: "मना किया",
  safetyLimit: "सुरक्षा सीमा पूरी",
  refusedBody: "कंपनी ने {n} बार विनम्र आग्रह के बाद भी मना किया। Advocall दो बार से ज़्यादा ज़ोर नहीं देता, इसलिए उसने कॉल खत्म की और नियामक के लिए शिकायत तैयार की।",
  unreachedBody: "इस कॉल पर शिकायत दर्ज नहीं हो पाई, इसलिए Advocall ने नियामक के लिए शिकायत तैयार की।",
  awaiting: "प्रतीक्षा",
  officialRef: "कंपनी का आधिकारिक रेफ़रेंस",
  insistHint: "Advocall औपचारिक शिकायत दर्ज करवाता है और रेफ़रेंस नंबर लेता है।",
  commitmentCaptured: "कंपनी का वादा दर्ज",
  acknowledged: "स्वीकार किया",
  noDate: "कोई तारीख नहीं दी",
  delayComp: "देरी का मुआवज़ा",
  notAgreed: "सहमति नहीं",
  readBack: "शिकायत नंबर दोहराया गया और कंपनी ने पुष्टि की",
  escalationTitle: "नियामक से शिकायत",
  escalationSub: "शिकायत पत्र तैयार करने वाला",
  escalationHint: "अगर कंपनी तारीख चूकती है या मना करती है, तो Advocall नियामक (RBI लोकपाल या राष्ट्रीय उपभोक्ता हेल्पलाइन) के लिए शिकायत पत्र बनाता है। दर्ज आप करते हैं।",
  preparing: "तैयार हो रहा है…",
  packetReady: "शिकायत दर्ज करने के लिए तैयार",
  portal: "पोर्टल",
  subject: "विषय",
  keyFacts: "मुख्य तथ्य",
  letter: "शिकायत पत्र",
  events: "घटनाएँ",
  noEvents: "अभी कोई घटना नहीं।",
  evCreated: "केस {id} बना",
  evStatus: "स्थिति: {s}",
  evRule: "नियम {id}: {title}",
  evClaimable: "कानूनी अधिकार लागू",
  evStandard: "सामान्य शिकायत",
  evCallStarted: "{leg} शुरू",
  evState: "कॉल का चरण: {s}",
  evCallEnded: "{leg} पूरी",
  evCallFailed: "{leg} विफल",
  evTicket: "शिकायत नंबर {t} दर्ज",
  evResolutionBy: "{d} तक समाधान",
  evEscalation: "शिकायत तैयार",
  evEscalationTo: "{to} के लिए",
  evSms: "{to} के लिए SMS",
  followupCall: "फ़ॉलो-अप कॉल",
  lines: "पंक्तियाँ",
  aiName: "Advocall AI",
  user: "यूज़र",
  company: "कंपनी",
  noTranscriptHint: "डेमो चलाएँ या लाइव कॉल शुरू करें, बातचीत यहाँ दिखेगी।",
  noSms: "अभी कोई SMS नहीं",
  smsHint: "कॉल के बाद Advocall ग्राहक को शिकायत नंबर और तारीख SMS करता है।",
  smsPreviewNote: "प्रीव्यू: यहाँ दिखाया गया, भेजा नहीं गया (SMS के लिए पंजीकृत सेंडर चाहिए)",
  statusIntake: "इंटेक",
  statusOpen: "खुला",
  statusCalling: "कॉल जारी",
  statusPromised: "वादा मिला",
  statusResolved: "सुलझ गया",
  statusEscalated: "आगे भेजा",
  statusFailed: "विफल",
  aiAdvocate: "AI उपभोक्ता वकील",
  emptyHint: "Advocall आपकी तरफ़ से कस्टमर केयर को कॉल करता है, होल्ड पर रुकता है, आपके अधिकार बताता है, और शिकायत नंबर व तारीख लेता है।",
  runHero: "UPI डेमो चलाएँ",
  runQuick: "छोटा डेमो (5× तेज़)",
  rightsTitle: "आपके अधिकारों की टाइमलाइन",
  rightsSub: "राइट्स इंजन द्वारा गणना",
  msIncident: "घटना",
  msDeadline: "कानूनी समय सीमा",
  msPromised: "कंपनी का वादा",
  msToday: "आज",
  msEscalate: "न सुलझे तो आगे शिकायत",
  liveCall: "लाइव कॉल",
  liveCallTitle: "असली कॉल शुरू करें",
  liveOff: "लाइव कॉल बंद हैं। .env.local में कुंजियाँ डालें और MODE=live करें।",
  yourPhone: "आपका फ़ोन (सिर्फ़ टीम)",
  yourName: "आपका नाम (वैकल्पिक)",
  callMe: "मुझे कॉल करें",
  calling: "कॉल हो रही है…",
  browserCall: "ब्राउज़र में बात करें",
};

const kn: Record<StringKey, string> = {
  appName: "Advocall",
  tagline: "ಹೋಲ್ಡ್‌ನಲ್ಲಿ ನಿಮ್ಮ AI ವಕೀಲ, ನೀವು ಕಾಯಬೇಕಾಗಿಲ್ಲ",
  liveCases: "ಲೈವ್ ಪ್ರಕರಣಗಳು",
  atStake: "ಅಪಾಯದಲ್ಲಿರುವ ಮೊತ್ತ",
  recovered: "ಮರಳಿ ಪಡೆದದ್ದು",
  ruleApplied: "ಅನ್ವಯಿಸಿದ ನಿಯಮ",
  deadline: "ಗಡುವು",
  daysLate: "ದಿನಗಳ ವಿಳಂಬ",
  compensation: "ಬಾಕಿ ಪರಿಹಾರ",
  ticket: "ದೂರು ಸಂಖ್ಯೆ",
  promisedBy: "ಭರವಸೆ ನೀಡಿದ ದಿನಾಂಕ",
  transcript: "ಲೈವ್ ಸಂಭಾಷಣೆ",
  timeline: "ಟೈಮ್‌ಲೈನ್",
  escalate: "ಗಡುವು ಮೀರಿದೆ: ಮುಂದೆ ದೂರು ನೀಡಿ",
  startDemo: "ಡೆಮೊ ಪ್ರಾರಂಭಿಸಿ",
  reset: "ಮರುಹೊಂದಿಸಿ",
  connected: "ಲೈವ್",
  disconnected: "ಆಫ್‌ಲೈನ್",
  noCases: "ಇನ್ನೂ ಯಾವುದೇ ಪ್ರಕರಣಗಳಿಲ್ಲ. Advocall ಗೆ ಕರೆ ಮಾಡಿ ಅಥವಾ ಡೆಮೊ ಪ್ರಾರಂಭಿಸಿ.",
  caseList: "ಪ್ರಕರಣಗಳ ಪಟ್ಟಿ",
  caseDetail: "ಪ್ರಕರಣದ ವಿವರ",
  liveOps: "ಲೈವ್ ಕಾರ್ಯಾಚರಣೆಗಳು",
  amountDisputed: "ವಿವಾದಿತ ಮೊತ್ತ",
  customer: "ಗ್ರಾಹಕ",
  reference: "ಉಲ್ಲೇಖ",
  callProgress: "ಕರೆಯ ಪ್ರಗತಿ",
  commitment: "ಭರವಸೆ",
  waitingTicket: "ದೂರು ಸಂಖ್ಯೆಗಾಗಿ ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ…",
  escalationPacket: "ದೂರು ಪತ್ರ (ಎಸ್ಕೆಲೇಶನ್ ಪ್ಯಾಕೆಟ್)",
  copyLetter: "ಪತ್ರ ನಕಲಿಸಿ",
  copied: "ನಕಲಿಸಲಾಗಿದೆ",
  smsSent: "ಬಳಕೆದಾರರಿಗೆ SMS (ಮುನ್ನೋಟ)",
  noTranscript: "ಇನ್ನೂ ಯಾವುದೇ ಸಂಭಾಷಣೆ ಇಲ್ಲ",
  computedByEngine: "ರೈಟ್ಸ್ ಎಂಜಿನ್‌ನಿಂದ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ, AI ನಿಂದ ಅಲ್ಲ",
  noLegalClaim: "ಯಾವುದೇ ಕಾನೂನು ಹಕ್ಕಿಲ್ಲ, ಸಾಮಾನ್ಯ ದೂರು ಮಾತ್ರ",
  source: "ಮೂಲ",
  intakeCall: "ಇನ್‌ಟೇಕ್ ಕರೆ",
  advocateCall: "ಕಂಪನಿಗೆ ಕರೆ",
  reportCall: "ವರದಿ ಕರೆ",
  activeCases: "ಸಕ್ರಿಯ ಪ್ರಕರಣಗಳು",
  committed: "ಭರವಸೆ ದೊರೆತಿದೆ",
  callsMade: "ಮಾಡಿದ ಕರೆಗಳು",
  present: "ಪ್ರಸ್ತುತಿ",

  demo: "ಡೆಮೊ",
  chooseDemo: "ಡೆಮೊ ಆಯ್ಕೆಮಾಡಿ",
  details: "ವಿವರ",
  chat: "ಸಂಭಾಷಣೆ",
  presentBanner: "ಪ್ರೊಜೆಕ್ಟರ್ ಮೋಡ್: ಲೈವ್ ಸಂಭಾಷಣೆ ಮತ್ತು ಕಾನೂನು ಹಕ್ಕುಗಳು",
  exitPresent: "ನಿರ್ಗಮಿಸಿ (P / Esc)",
  inFlight: "ನಡೆಯುತ್ತಿದೆ",
  disputed: "ವಿವಾದಿತ",
  ticketConfirmed: "ದೂರು ಸಂಖ್ಯೆ ದೊರೆತಿದೆ",
  voiceLegs: "ಧ್ವನಿ ಕರೆಗಳು",
  newestFirst: "ಹೊಸದು ಮೊದಲು",
  incident: "ಘಟನೆ",
  notProvided: "ನೀಡಿಲ್ಲ",
  issue: "ಸಮಸ್ಯೆ",
  matchingRule: "ಪ್ರಕರಣಕ್ಕೆ ನಿಯಮ ಹುಡುಕಲಾಗುತ್ತಿದೆ…",
  none: "ಇಲ್ಲ",
  nDaysLate: "{n} ದಿನ ತಡ",
  oneDayLate: "1 ದಿನ ತಡ",
  onTime: "ಸಮಯಕ್ಕೆ",
  advocateProgress: "ಕಂಪನಿ ಕರೆಯ ಪ್ರಗತಿ",
  advocateProgressSub: "IVR, ಹೋಲ್ಡ್ ಮತ್ತು ಮಾತುಕತೆ, ಹಂತ ಹಂತವಾಗಿ",
  live: "ಲೈವ್",
  done: "ಮುಗಿದಿದೆ",
  pending: "ಬಾಕಿ",
  queued: "ಸರದಿಯಲ್ಲಿ",
  ringing: "ರಿಂಗ್ ಆಗುತ್ತಿದೆ",
  failed: "ವಿಫಲ",
  outcome: "ಫಲಿತಾಂಶ",
  stepDISCLOSE: "ಪರಿಚಯ",
  stepNAVIGATE: "IVR ಮೆನು",
  stepHOLD: "ಹೋಲ್ಡ್",
  stepSTATE_CASE: "ಪ್ರಕರಣ ವಿವರಣೆ",
  stepASK: "ಸಂಖ್ಯೆ ಕೇಳಿತು",
  stepPUSH_BACK: "ಒತ್ತಾಯ",
  stepVERIFY: "ಪರಿಶೀಲನೆ",
  stepCAPTURE: "ದಾಖಲು",
  stepCLOSE: "ಮುಕ್ತಾಯ",
  noTicket: "ದೂರು ಸಂಖ್ಯೆ ಸಿಗಲಿಲ್ಲ",
  noTicketSub: "ಕಂಪನಿ ದೂರು ದಾಖಲಿಸಲಿಲ್ಲ",
  declined: "ನಿರಾಕರಿಸಲಾಗಿದೆ",
  safetyLimit: "ಸುರಕ್ಷತಾ ಮಿತಿ ತಲುಪಿದೆ",
  refusedBody: "{n} ಬಾರಿ ವಿನಯದಿಂದ ಒತ್ತಾಯಿಸಿದ ನಂತರವೂ ಕಂಪನಿ ನಿರಾಕರಿಸಿತು. Advocall ಎರಡು ಬಾರಿಗಿಂತ ಹೆಚ್ಚು ಒತ್ತಾಯಿಸುವುದಿಲ್ಲ, ಆದ್ದರಿಂದ ಕರೆ ಮುಗಿಸಿ ನಿಯಂತ್ರಕರಿಗೆ ದೂರು ಸಿದ್ಧಪಡಿಸಿತು.",
  unreachedBody: "ಈ ಕರೆಯಲ್ಲಿ ದೂರು ದಾಖಲಾಗಲಿಲ್ಲ, ಆದ್ದರಿಂದ Advocall ನಿಯಂತ್ರಕರಿಗೆ ದೂರು ಸಿದ್ಧಪಡಿಸಿತು.",
  awaiting: "ನಿರೀಕ್ಷೆ",
  officialRef: "ಕಂಪನಿಯ ಅಧಿಕೃತ ಉಲ್ಲೇಖ",
  insistHint: "Advocall ಅಧಿಕೃತ ದೂರು ದಾಖಲಿಸಲು ಕೇಳುತ್ತದೆ ಮತ್ತು ಉಲ್ಲೇಖ ಸಂಖ್ಯೆಯನ್ನು ಪಡೆಯುತ್ತದೆ.",
  commitmentCaptured: "ಭರವಸೆ ದಾಖಲಾಗಿದೆ",
  acknowledged: "ಒಪ್ಪಿಕೊಳ್ಳಲಾಗಿದೆ",
  noDate: "ದಿನಾಂಕ ನೀಡಿಲ್ಲ",
  delayComp: "ವಿಳಂಬ ಪರಿಹಾರ",
  notAgreed: "ಒಪ್ಪಿಲ್ಲ",
  readBack: "ದೂರು ಸಂಖ್ಯೆಯನ್ನು ಮತ್ತೆ ಓದಿ ಕಂಪನಿ ದೃಢಪಡಿಸಿದೆ",
  escalationTitle: "ನಿಯಂತ್ರಕರಿಗೆ ದೂರು",
  escalationSub: "ದೂರು ಪತ್ರ ತಯಾರಕ",
  escalationHint: "ಕಂಪನಿ ದಿನಾಂಕ ತಪ್ಪಿಸಿದರೆ ಅಥವಾ ನಿರಾಕರಿಸಿದರೆ, Advocall ನಿಯಂತ್ರಕರಿಗೆ (RBI ಓಂಬುಡ್ಸ್‌ಮನ್ ಅಥವಾ ರಾಷ್ಟ್ರೀಯ ಗ್ರಾಹಕ ಸಹಾಯವಾಣಿ) ದೂರು ಪತ್ರ ಸಿದ್ಧಪಡಿಸುತ್ತದೆ. ಸಲ್ಲಿಸುವುದು ನೀವು.",
  preparing: "ಸಿದ್ಧವಾಗುತ್ತಿದೆ…",
  packetReady: "ಸಲ್ಲಿಸಲು ದೂರು ಸಿದ್ಧ",
  portal: "ಪೋರ್ಟಲ್",
  subject: "ವಿಷಯ",
  keyFacts: "ಮುಖ್ಯ ಅಂಶಗಳು",
  letter: "ದೂರು ಪತ್ರ",
  events: "ಘಟನೆಗಳು",
  noEvents: "ಇನ್ನೂ ಯಾವುದೇ ಘಟನೆಗಳಿಲ್ಲ.",
  evCreated: "ಪ್ರಕರಣ {id} ರಚಿಸಲಾಗಿದೆ",
  evStatus: "ಸ್ಥಿತಿ: {s}",
  evRule: "ನಿಯಮ {id}: {title}",
  evClaimable: "ಕಾನೂನು ಹಕ್ಕು ಅನ್ವಯಿಸುತ್ತದೆ",
  evStandard: "ಸಾಮಾನ್ಯ ದೂರು",
  evCallStarted: "{leg} ಆರಂಭ",
  evState: "ಕರೆಯ ಹಂತ: {s}",
  evCallEnded: "{leg} ಮುಗಿದಿದೆ",
  evCallFailed: "{leg} ವಿಫಲ",
  evTicket: "ದೂರು ಸಂಖ್ಯೆ {t} ದಾಖಲು",
  evResolutionBy: "{d} ಒಳಗೆ ಪರಿಹಾರ",
  evEscalation: "ದೂರು ಸಿದ್ಧ",
  evEscalationTo: "{to} ಗಾಗಿ",
  evSms: "{to} ಗೆ SMS",
  followupCall: "ಫಾಲೋ-ಅಪ್ ಕರೆ",
  lines: "ಸಾಲುಗಳು",
  aiName: "Advocall AI",
  user: "ಬಳಕೆದಾರ",
  company: "ಕಂಪನಿ",
  noTranscriptHint: "ಡೆಮೊ ಪ್ರಾರಂಭಿಸಿ ಅಥವಾ ಲೈವ್ ಕರೆ ಮಾಡಿ, ಸಂಭಾಷಣೆ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.",
  noSms: "ಇನ್ನೂ SMS ಇಲ್ಲ",
  smsHint: "ಕರೆಗಳ ನಂತರ Advocall ಗ್ರಾಹಕರಿಗೆ ದೂರು ಸಂಖ್ಯೆ ಮತ್ತು ದಿನಾಂಕವನ್ನು SMS ಮಾಡುತ್ತದೆ.",
  smsPreviewNote: "ಮುನ್ನೋಟ: ಇಲ್ಲಿ ತೋರಿಸಲಾಗಿದೆ, ಕಳುಹಿಸಿಲ್ಲ (SMS ಗೆ ನೋಂದಾಯಿತ ಕಳುಹಿಸುವವರು ಬೇಕು)",
  statusIntake: "ಇನ್‌ಟೇಕ್",
  statusOpen: "ತೆರೆದಿದೆ",
  statusCalling: "ಕರೆ ನಡೆಯುತ್ತಿದೆ",
  statusPromised: "ಭರವಸೆ ದೊರೆತಿದೆ",
  statusResolved: "ಪರಿಹಾರವಾಗಿದೆ",
  statusEscalated: "ಮುಂದೆ ಕಳುಹಿಸಲಾಗಿದೆ",
  statusFailed: "ವಿಫಲ",
  aiAdvocate: "AI ಗ್ರಾಹಕ ವಕೀಲ",
  emptyHint: "Advocall ನಿಮ್ಮ ಪರವಾಗಿ ಗ್ರಾಹಕ ಸೇವೆಗೆ ಕರೆ ಮಾಡುತ್ತದೆ, ಹೋಲ್ಡ್‌ನಲ್ಲಿ ಕಾಯುತ್ತದೆ, ನಿಮ್ಮ ಹಕ್ಕುಗಳನ್ನು ಹೇಳುತ್ತದೆ ಮತ್ತು ದೂರು ಸಂಖ್ಯೆ ಹಾಗೂ ದಿನಾಂಕ ಪಡೆಯುತ್ತದೆ.",
  runHero: "UPI ಡೆಮೊ ಪ್ರಾರಂಭಿಸಿ",
  runQuick: "ಚಿಕ್ಕ ಡೆಮೊ (5× ವೇಗ)",
  rightsTitle: "ನಿಮ್ಮ ಹಕ್ಕುಗಳ ಟೈಮ್‌ಲೈನ್",
  rightsSub: "ರೈಟ್ಸ್ ಎಂಜಿನ್ ಲೆಕ್ಕಾಚಾರ",
  msIncident: "ಘಟನೆ",
  msDeadline: "ಕಾನೂನು ಗಡುವು",
  msPromised: "ಕಂಪನಿಯ ಭರವಸೆ",
  msToday: "ಇಂದು",
  msEscalate: "ಪರಿಹಾರವಾಗದಿದ್ದರೆ ಮುಂದೆ ದೂರು",
  liveCall: "ಲೈವ್ ಕರೆ",
  liveCallTitle: "ನಿಜವಾದ ಕರೆ ಪ್ರಾರಂಭಿಸಿ",
  liveOff: "ಲೈವ್ ಕರೆಗಳು ಆಫ್ ಆಗಿವೆ. .env.local ನಲ್ಲಿ ಕೀಗಳನ್ನು ಸೇರಿಸಿ ಮತ್ತು MODE=live ಮಾಡಿ.",
  yourPhone: "ನಿಮ್ಮ ಫೋನ್ (ತಂಡ ಮಾತ್ರ)",
  yourName: "ನಿಮ್ಮ ಹೆಸರು (ಐಚ್ಛಿಕ)",
  callMe: "ನನಗೆ ಕರೆ ಮಾಡಿ",
  calling: "ಕರೆ ಮಾಡಲಾಗುತ್ತಿದೆ…",
  browserCall: "ಬದಲಾಗಿ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಮಾತನಾಡಿ",
};

export const STRINGS: Record<Lang, Record<StringKey, string>> = { en, hi, kn };

export function t(key: StringKey, lang: Lang = "en"): string {
  return STRINGS[lang]?.[key] ?? STRINGS.en[key] ?? key;
}

/** fill("{n} days late", { n: 3 }) -> "3 days late" */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (m, k: string) => (k in values ? String(values[k]) : m));
}
