// Owner: YASO. Dashboard UI labels in 3 languages. Vaishnavi's components call t("key", lang).
import type { Lang } from "@/types";

const en = {
  appName: "Advocall",
  tagline: "Your AI advocate on hold, so you don't have to be",
  liveCases: "Live cases",
  atStake: "At stake",
  recovered: "Recovered",
  ruleApplied: "Rule applied",
  deadline: "Deadline",
  daysLate: "Days late",
  compensation: "Compensation owed",
  ticket: "Ticket number",
  promisedBy: "Promised by",
  transcript: "Live transcript",
  timeline: "Timeline",
  escalate: "Deadline missed: escalate",
  startDemo: "Run demo",
  reset: "Reset",
  connected: "Live",
  disconnected: "Offline",
  noCases: "No cases yet. Call Advocall or run a demo.",
  caseList: "Cases",
  caseDetail: "Case detail",
  liveOps: "Live operations",
  amountDisputed: "Amount disputed",
  customer: "Customer",
  reference: "Reference",
  callProgress: "Call progress",
  commitment: "Commitment",
  waitingTicket: "Waiting for ticket number…",
  escalationPacket: "Escalation packet",
  copyLetter: "Copy letter",
  copied: "Copied",
  smsSent: "SMS sent to user",
  noTranscript: "No conversation yet",
  computedByEngine: "Computed by rights engine, not by AI",
  noLegalClaim: "No legal claim, standard complaint only",
  source: "Source",
  intakeCall: "Intake call",
  advocateCall: "Call to company",
  reportCall: "Report-back call",
  activeCases: "Active cases",
  committed: "Committed",
  callsMade: "Calls made",
  present: "Present",
};

export type StringKey = keyof typeof en;

const hi: Record<StringKey, string> = {
  appName: "Advocall",
  tagline: "होल्ड पर आपका AI वकील, ताकि आपको इंतज़ार न करना पड़े",
  liveCases: "लाइव केस",
  atStake: "दांव पर राशि",
  recovered: "वापस मिला",
  ruleApplied: "लागू नियम",
  deadline: "समय सीमा",
  daysLate: "दिन की देरी",
  compensation: "बकाया मुआवज़ा",
  ticket: "शिकायत नंबर",
  promisedBy: "वादा की गई तारीख",
  transcript: "लाइव बातचीत",
  timeline: "टाइमलाइन",
  escalate: "समय सीमा निकल गई: आगे शिकायत करें",
  startDemo: "डेमो चलाएँ",
  reset: "रीसेट",
  connected: "लाइव",
  disconnected: "ऑफ़लाइन",
  noCases: "अभी कोई केस नहीं। Advocall को कॉल करें या डेमो चलाएँ।",
  caseList: "केस सूची",
  caseDetail: "केस विवरण",
  liveOps: "लाइव ऑपरेशन्स",
  amountDisputed: "विवादित राशि",
  customer: "ग्राहक",
  reference: "रेफ़रेंस",
  callProgress: "कॉल प्रगति",
  commitment: "कंपनी का वादा",
  waitingTicket: "शिकायत नंबर की प्रतीक्षा…",
  escalationPacket: "शिकायत पत्र (एस्केलेशन पैकेट)",
  copyLetter: "पत्र कॉपी करें",
  copied: "कॉपी हो गया",
  smsSent: "यूज़र को भेजा गया SMS",
  noTranscript: "अभी कोई बातचीत नहीं",
  computedByEngine: "राइट्स इंजन द्वारा निर्धारित, AI द्वारा नहीं",
  noLegalClaim: "कोई वैधानिक दावा नहीं, केवल सामान्य शिकायत",
  source: "स्रोत",
  intakeCall: "इंटेक कॉल",
  advocateCall: "कंपनी को कॉल",
  reportCall: "रिपोर्ट-बैक कॉल",
  activeCases: "सक्रिय केस",
  committed: "वादा मिला",
  callsMade: "की गई कॉल",
  present: "उपस्थित",
};

const kn: Record<StringKey, string> = {
  appName: "Advocall",
  tagline: "ಹೋಲ್ಡ್‌ನಲ್ಲಿ ನಿಮ್ಮ AI ವಕೀಲ, ನೀವು ಕಾಯಬೇಕಾಗಿಲ್ಲ",
  liveCases: "ಲೈವ್ ಪ್ರಕರಣಗಳು",
  atStake: "ಅಪಾಯದಲ್ಲಿರುವ ಮೊತ್ತ",
  recovered: "ಮರಳಿ ಪಡೆದದ್ದು",
  ruleApplied: "ಅನ್ವಯಿಸಿದ ನಿಯಮ",
  deadline: "ಗಡುವು",
  daysLate: "ದಿನಗಳ ವಿಳಂಬ",
  compensation: "ಬಾಕಿ ಪರಿಹಾರ",
  ticket: "ದೂರು ಸಂಖ್ಯೆ",
  promisedBy: "ಭರವಸೆ ನೀಡಿದ ದಿನಾಂಕ",
  transcript: "ಲೈವ್ ಸಂಭಾಷಣೆ",
  timeline: "ಟೈಮ್‌ಲೈನ್",
  escalate: "ಗಡುವು ಮೀರಿದೆ: ಮುಂದೆ ದೂರು ನೀಡಿ",
  startDemo: "ಡೆಮೊ ಪ್ರಾರಂಭಿಸಿ",
  reset: "ಮರುಹೊಂದಿಸಿ",
  connected: "ಲೈವ್",
  disconnected: "ಆಫ್‌ಲೈನ್",
  noCases: "ಇನ್ನೂ ಯಾವುದೇ ಪ್ರಕರಣಗಳಿಲ್ಲ. Advocall ಗೆ ಕರೆ ಮಾಡಿ ಅಥವಾ ಡೆಮೊ ಪ್ರಾರಂಭಿಸಿ.",
  caseList: "ಪ್ರಕರಣಗಳ ಪಟ್ಟಿ",
  caseDetail: "ಪ್ರಕರಣದ ವಿವರ",
  liveOps: "ಲೈವ್ ಕಾರ್ಯಾಚರಣೆಗಳು",
  amountDisputed: "ವಿವಾದಿತ ಮೊತ್ತ",
  customer: "ಗ್ರಾಹಕ",
  reference: "ಉಲ್ಲೇಖ",
  callProgress: "ಕರೆಯ ಪ್ರಗತಿ",
  commitment: "ಭರವಸೆ",
  waitingTicket: "ದೂರು ಸಂಖ್ಯೆಗಾಗಿ ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ…",
  escalationPacket: "ದೂರು ಪತ್ರ (ಎಸ್ಕೆಲೇಶನ್ ಪ್ಯಾಕೆಟ್)",
  copyLetter: "ಪತ್ರ ನಕಲಿಸಿ",
  copied: "ನಕಲಿಸಲಾಗಿದೆ",
  smsSent: "ಬಳಕೆದಾರರಿಗೆ SMS ಕಳುಹಿಸಲಾಗಿದೆ",
  noTranscript: "ಇನ್ನೂ ಯಾವುದೇ ಸಂಭಾಷಣೆ ಇಲ್ಲ",
  computedByEngine: "ರೈಟ್ಸ್ ಎಂಜಿನ್‌ನಿಂದ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ, AI ನಿಂದ ಅಲ್ಲ",
  noLegalClaim: "ಯಾವುದೇ ಕಾನೂನು ಹಕ್ಕಿಲ್ಲ, ಸಾಮಾನ್ಯ ದೂರು ಮಾತ್ರ",
  source: "ಮೂಲ",
  intakeCall: "ಇನ್‌ಟೇಕ್ ಕರೆ",
  advocateCall: "ಕಂಪನಿಗೆ ಕರೆ",
  reportCall: "ವರದಿ ಕರೆ",
  activeCases: "ಸಕ್ರಿಯ ಪ್ರಕರಣಗಳು",
  committed: "ಭರವಸೆ ದೊರೆತಿದೆ",
  callsMade: "ಮಾಡಿದ ಕರೆಗಳು",
  present: "ಹಾಜರಿದ್ದಾರೆ",
};

export const STRINGS: Record<Lang, Record<StringKey, string>> = { en, hi, kn };

export function t(key: StringKey, lang: Lang = "en"): string {
  return STRINGS[lang]?.[key] ?? STRINGS.en[key] ?? key;
}
